# compose 파일 버전
version: '0.0.1'
networks:
  e-commerce_default:
    driver: bridge

services:
  # 서비스 명
  postgresql:
    # 사용할 이미지
    image: postgres
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: postgres
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - '5432:5432'
    # 환경 변수 설정
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mall
    networks:
      - e-commerce_default
    # 볼륨 설정
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # 서비스 명
  pgadmin:
    # 사용할 이미지
    image: dpage/pgadmin4
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: pgadmin4
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - '5050:80'
    # 환경 변수 설정
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - e-commerce_default
    # 볼륨 설정
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
  ecommerce:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/var/app
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_DB: mall
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - e-commerce_default
    command: npm run start:prod
